### ISSUE TITLE
Inquiry About Downloading Maximum Resolution Images with Artvee Pro Membership

### ISSUE THREAD

**Issue by luckykellan** [zduclos/artvee-scraper#2]
I recently subscribed to a Pro membership on Artvee, does the artvee-scraper support downloading images at the maximum resolution available to Pro members?

**Comment by canvachad** [comment]
> I recently subscribed to a Pro membership on Artvee, does the artvee-scraper support downloading images at the maximum resolution available to Pro members?

Hello, did downloading at the maximum resolution with a pro membership work for you?
